# Generated by Django 4.2.9 on 2026-03-15 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveSmallIntegerField(verbose_name='Ряд')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Место')),
                ('category', models.CharField(default='standard', max_length=50, verbose_name='Категория')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('status', models.CharField(choices=[('FREE', 'Свободно'), ('RESERVED', 'Забронировано'), ('SOLD', 'Продано')], db_index=True, default='FREE', max_length=10, verbose_name='Статус')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='events.event', verbose_name='Событие')),
            ],
            options={
                'db_table': 'seats',
                'indexes': [models.Index(fields=['event', 'status'], name='seats_event_i_4f4e46_idx')],
                'unique_together': {('event', 'row', 'number')},
            },
        ),
    ]
