# Generated by Django 4.2.9 on 2026-03-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('venue', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('date', models.DateTimeField(db_index=True, verbose_name='Дата события')),
                ('total_seats', models.PositiveIntegerField(default=0, verbose_name='Всего мест')),
                ('image_url', models.URLField(blank=True, verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['date'],
            },
        ),
    ]
